apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: rabbit-mq
spec:
    replicas: 1
    template:
        metadata:
            labels:
              app: rabbit-mq
              tier: messaging
        spec:
            containers:
            - name: rabbit-mq
              image: bitnami/rabbitmq:latest
              env:
              - name: RABBITMQ_USERNAME
                value: hystrixUser
              - name: RABBITMQ_PASSWORD
                value: password
              ports:
              - containerPort: 5672
              - containerPort: 15672

---

apiVersion: v1
kind: Service
metadata:
    name: rabbit-mq-gateway
    labels:
        app: rabbit-mq
        tier: messaging
spec:
    type: LoadBalancer
    ports:
    - name: web
        port: 15672
        protocol: TCP
    - name: tcp
        port: 5672
        protocol: TCP
    selector:
        app: rabbit-mq
        tier: messaging